# Generated by Django 3.2.9 on 2024-10-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(upload_to='main.storage.vercelStorage.VercelBlobStorage')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_agricultor', models.IntegerField()),
                ('classificacao', models.DecimalField(decimal_places=1, max_digits=3)),
                ('tipo_produto', models.CharField(max_length=100)),
                ('tipo_medida', models.CharField(max_length=50)),
            ],
        ),
    ]
